# The URL the site will be built for
base_url = "https://vala.dev"

# The site title and description; used in feeds by default.
title = "Vala Programming Language"
description = "Vala is an object-oriented programming language with a self-hosting compiler that generates C code and uses the GObject type system."

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

# The filename to use for the feed. Used as the template filename, too.
# Defaults to "atom.xml", which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filename = "atom.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
extra_syntaxes_and_themes = ["syntaxes"]

highlight_code = true

highlight_theme = "css"

highlight_themes_css = [
  { theme = "OneHalfLight", filename = "css/syntax-theme-light.css" },
  { theme = "OneHalfDark", filename = "css/syntax-theme-dark.css" },
]

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true


# Optional translation object for the default language
# Example:
#     default_language = "fr"
#
#     [translations]
#     title = "Un titre"
#
[translations]
bypass_block = "Skip to main content"
home = "Home"
about = "About"
documentation = "Docs"
community = "Community"
wiki = "wiki"
tagline = "A Familiar Way To Develop Applications"
get_started = "Get Started"
view_source_code = "View Source Code"
why_vala = "Why Vala?"

productivity = "Productivity"
productivity_description = "Comfortably write your code in an object-oriented way with high level abstractions, while having access to deep integrations with GNOME technolgies such as: GObject, GTK and more!"

performance = "Performance"
performance_description = "Vala compiles code down to blazingly fast, fully native binaries. You're also able to reuse existing C Code in your Vala programs as well as generate C Code from Vala."

open_source = "Open-Source"
open_source_description = "Vala is free and open-source software. It has a great community that contributes to the compiler and develops lots of tooling."
tooling_documentation = "Tooling Documentation"

learn_more_about_vala = "Learn more about Vala"
what_can_you_build = "What can you build?"

gui_applications = "GUI Applications"
gui_applications_description = "Perfect integration of GTK, Libadwaita and Granite makes development super simple. Publish easily your apps on Flathub without bloated packages."
gnome_tutorial = "GNOME Getting Started Tutorial"
elementary_tutorial = "elementary OS App Tutorial"

command_line_programs = "Command Line Programs"
command_line_programs_description = "Use a large standard library and use loads of other libraries available for use in Vala."

libraries = "Libraries"
libraries_description = "Provide bindings for many other languages and API documentation without manual work. Also, dynamic and static linking are both supported."

whats_new = "What's new?"
view_blog = "View Blog"

showcase = "Showcase"
view_more_vala_projects = "View More Vala Projects"

forums = "Forums"
forums_description = "Ask questions related to Vala in the GNOME Discourse forums under the &quot;vala&quot; tag."
discourse_forums = "Discourse Forums"

internals_chat = "Internals Chat"
internals_chat_description = "Talk to the developers or ask questions about how to contribute to Vala, use the Vala Matrix channel. It also has a IRC bridge."
matrix_room = "Matrix Room"

community_server = "Community Server"
community_server_description = "Connect with the community on the Discord server."
discord_server = "Discord Server"

social_media = "Social Media"
follow_vala_project = "Follow the Vala project across these platforms"
made_by_vala_community = "Made by the Vala Community"
view_website_source_code = "View The Website's Source Code"
license_description = "This work is licensed under a"

default_image_description = "Purple background with white text on center that says 'Vala'."

page_not_found = "Error 404 - Page Not Found"
page_not_found_description = "The URL may be misspelled or the page you requested no longer exists."
go_home = "Go Home"


# Additional languages definition
# You can define language specific config values and translations: 
# title, description, generate_feed, feed_filename, taxonomies, build_search_index
# as well as its own search configuration and translations (see above for details on those)
[languages]

[languages.fr]
generate_feed = true # there will be a feed for French content
build_search_index = true

[languages.fr.translations]
bypass_block = "menu principal"
home = "Home"
about = "A propos"
documentation = "Docs"
community = "Community"
wiki = "wiki"
tagline = "A Familiar Way To Develop Applications"
get_started = "Commencer"
view_source_code = "Afficher le code source"
why_vala = "Pourquoi Vala?"

productivity = "productivité"
productivity_description = "Écrivez confortablement votre code de manière orientée objet avec des abstractions de haut niveau, tout en ayant accès à des intégrations profondes avec les technologies GNOME telles que : GObject, GTK et plus encore !"

performance = "Performance"
performance_description = "Vala compile le code jusqu'à des binaires entièrement natifs extrêmement rapides. Vous pouvez également réutiliser le code C existant dans vos programmes Vala ainsi que générer du code C à partir de Vala."

open_source = "Open-Source" 
open_source_description = "Vala est un logiciel gratuit et open-source. Il a une grande communauté qui contribue au compilateur et développe de nombreux outils."
tooling_documentation = "Documentation des outils vala"

learn_more_about_vala = "En savoir plus sur Vala"
what_can_you_build = "Que voulez-vous coder ?"

gui_applications = "Applications Graphique"
gui_applications_description = "L'intégration parfaite de GTK, Libadwaita et Granite rend le développement super simple. Publiez facilement vos applications sur Flathub sans paquets trop lourd."
gnome_tutorial = "tutoriel de GNOME"
elementary_tutorial = "tutoriel d'elementary OS"

command_line_programs = "Programmes CLI/TUI"
command_line_programs_description = "Utilisez une grande bibliothèque standard et utilisez des charges d'autres bibliothèques disponibles pour une utilisation dans Vala."

libraries = "Librairies"
libraries_description = "Fournir des liaisons pour d'autres langages et de la documentation API sans travail manuel. Ainsi que les liaisons dynamiques et statiques des libs sont prises en charge"

whats_new = "Quoi de neuf?"
view_blog = "Blog"

showcase = "Vitrine"
view_more_vala_projects = "Voir plus de projets Vala"

forums = "Forums"
forums_description = "Posez des questions relatives à Vala dans les forums GNOME sous l'etiquette vala"
discourse_forums = "Discourse Forums"

internals_chat = "Internals Chat"
internals_chat_description = "Parlez aux développeurs ou posez des questions sur la façon de contribuer à Vala, utilisez le canal Vala Matrix. Il dispose également d'un canal IRC."
matrix_room = "Canal Matrix"

community_server = "Serveur communautaire"
community_server_description = "Connectez-vous avec la communauté sur le serveur Discord."
discord_server = "Discord Serveur"

social_media = "Réseau sociaux"
follow_vala_project = "Suivez le projet Vala sur ces plateformes"
made_by_vala_community = "Site web communautaire"
view_website_source_code = "Code souce du site"
license_description = "Ce site est sous licence:"

default_image_description = "un fond violet avec du texte blanc centré c'est signé 'Vala'."

page_not_found = "Erreur 404 - Page non trouvé"
page_not_found_description = "la page que vous avez demandée n'existe plus."
go_home = "Go Home"

[extra]
# Put all your custom variables here

docs_url="https://wiki.gnome.org/Projects/Vala/Documentation"

tutorial_url = "https://wiki.gnome.org/Projects/Vala/Documentation#Getting_Started"

language_source_code_url = "https://gitlab.gnome.org/GNOME/vala"

site_source_code_url = "https://github.com/vala-lang/vala-www"

license_url = "https://creativecommons.org/licenses/by-sa/4.0/"

wiki_url = "https://wiki.gnome.org/Projects/Vala/"

[extra.features]

gnome_developer_tutorial = "https://developer.gnome.org/documentation/tutorials/beginners/getting_started.html"

elementary_app_tutorial = "https://docs.elementary.io/develop/"


[extra.showcase]

awesome_vala_url = "https://github.com/desiderantes/awesome-vala"

[extra.tooling]

vala_language_server = "https://github.com/vala-lang/vala-language-server"

vala_lint = "https://github.com/vala-lang/vala-lint"

valadoc = "https://wiki.gnome.org/Projects/Valadoc"

gnome_builder = "https://apps.gnome.org/en-GB/app/org.gnome.Builder/"

vs_code = "https://marketplace.visualstudio.com/items?itemName=prince781.vala"

vim = "https://github.com/arrufat/vala.vim"

meson = "https://mesonbuild.com/Vala.html"

documentation = "https://wiki.gnome.org/Projects/Vala/Tools"

[extra.socials]

discourse = "https://discourse.gnome.org/tag/vala"

matrix = "https://matrix.to/#/#_gimpnet_#vala:gnome.org"

mastodon = "https://mastodon.social/@vala_lang"

discord = "https://discord.gg/YFAzjSVHt7"

telegram = "https://t.me/vala_lang"

twitter = "https://www.twitter.com/vala_lang"

reddit = "https://www.reddit.com/r/vala"
