# The URL the site will be built for
base_url = "https://vala.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "css"

highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "css/syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "css/syntax-theme-light.css" },
]

extra_syntaxes_and_themes = ["syntaxes"]

[extra]
# Put all your custom variables here
docs_url="https://lwildberg.pages.gitlab.gnome.org/vala-tutorial"

tutorial_url="https://lwildberg.pages.gitlab.gnome.org/vala-tutorial/guides/installation.html"

language_source_code_url="https://gitlab.gnome.org/GNOME/vala"

site_source_code_url="https://github.com/colinkiama/vala-www"

license_url="http://creativecommons.org/licenses/by-sa/4.0/"
