# The URL the site will be built for
base_url = "https://vala.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
extra_syntaxes_and_themes = ["syntaxes"]

highlight_code = true

highlight_theme = "css"

highlight_themes_css = [
  { theme = "OneHalfLight", filename = "css/syntax-theme-light.css" },
  { theme = "OneHalfDark", filename = "css/syntax-theme-dark.css" },
]

[extra]
# Put all your custom variables here
docs_url="https://lwildberg.pages.gitlab.gnome.org/vala-tutorial"

tutorial_url = "https://lwildberg.pages.gitlab.gnome.org/vala-tutorial/guides/installation.html"

language_source_code_url = "https://gitlab.gnome.org/GNOME/vala"

site_source_code_url = "https://github.com/colinkiama/vala-www"

license_url = "https://creativecommons.org/licenses/by-sa/4.0/"

[extra.showcase]

awesome_vala_url = "https://github.com/desiderantes/awesome-vala"

[extra.tooling]

vala_language_server = "https://github.com/vala-lang/vala-language-server"

vala_lint = "https://github.com/vala-lang/vala-lint"

vala_github_org = "https://github.com/vala-lang"

[extra.socials]

discourse = "https://discourse.gnome.org/tag/vala"

matrix = "https://matrix.to/#/#_gimpnet_#vala:gnome.org"

discord = "https://discord.gg/YFAzjSVHt7"

telegram = "https://t.me/codefaq"

twitter = "https://www.twitter.com/vala_lang"

reddit = "https://www.reddit.com/r/vala"
